<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Polaris</AssemblyName>
    <RootNamespace>Polaris</RootNamespace>
    <Version>1.1.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Product>Polaris</Product>
    <Description>Windows proxy client with delay test, location and security reports</Description>
  </PropertyGroup>
</Project>
